load('data.mat')

%Default payload
pkgSize = [1 1 1]*0.15; % m
pkgDensity = 0.1/(0.15^3); % kg/m^3


%Default scenario
scenario = 1;
number_waypoints = 10; 

%% Mass of the individual parts of the Quadcopter
m_arm1 = 0.0589152; % kg
m_arm2 = 0.0589152; % kg
m_arm3 = 0.0589152; % kg
m_arm4 = 0.0589152; % kg
m_flight_computer = 38e-03; % kg
m_top_plate = 0.0317292; % kg
m_top_plate1 = 0.0317292; % kg
m_motor = 51e-03; % kg
m_motor_base = 3.84845e-06; % kg
m_motor_cap = 0.000930841; % kg
m_propeller = 0.0748404; % kg
m_inertia = 0.000450523; % kg
m_total = m_arm1 + m_arm2 + m_arm3 + m_arm4 + m_flight_computer + m_top_plate + m_top_plate1 + 4*(m_motor + m_motor_base + m_motor_cap + m_propeller + m_inertia);

%% Ambient Condition
Temp = 298.15;                                          %k, equavalent to 25 degree
rho_air = 1.225;                                          % kg/m^3, air density at room temperature
miu_air = 1.825e-5;                                    % kg/(ms) dynamic viscosity of air at room temperature
pr_air = 0.7323;                                           %prandtl number
k_air = 0.02476;                                           % W/(m*K) thermal conductivity of air under room temperature

%% Geometry Property

% Size of the ground
planex = 12.5;                    % m
planey = 8.5;                    % m
planedepth = 0.2;         % m, distance from plane to the reference frame

% Size of propeller
propx = 0.01;            % m, lenght of propeller along x-axis
propy = 0.2;              % m
propz = 0.001;          % m 

% initial position of drone
x0 = -2;
y0 = -2;
z0 = 0.05;
initialAltitude = 0.06;                  % m, height above the reference frame
xrot = 0;               % deg, angle against x-axis
yrot = 0;               % deg, angle against y-axis
zrot = 0;               % deg, angle aganist z-axis

% Battery scale
l_bat =sqrt( (73e-3)^2+(28e-3)^2);              % length of battery in meter

% Battery Capacity
Ah = 7.6;

%% Material Property
% Assuming the arm of the drone is manufractured by 3D Printing, the ideal
% material is PLA, safe, lighr and cheap, the only concern is its thermal
% property

rho_nylon = 1.41;             % g/cm^3 
rho_glass = 2.56;              % g/cm^3 glass fibre
rho_pla = 1.25;                 % g/cm^3 
rho_cfrp = 6.32/3;               % g/cm^3
rho_al = 2.66;                  % g/cm^3, alluminium alloy 5086

%% Mechanical Property
T = 1;                     % Nm, the torque produced by single motor
N1 =  1.61;                 % N, the thrust generated by the single blade
N2 = 1.61;
N3 =  1.61;
N4 = 1.61;

% rotation friction between motor and blade

BreakTor = 40;
BreakVel = 2;
CombFric = 10;
VisFric = 2;

% contact force between landing support and ground
StatFricCoeff = 0.3;
DynaFricCoeff = 0.5;
contactDamping = 600000/2;
contactStiffness = 3.5e8;

%% Graphic Property
Opacity = 0;

T_stop = 0;                % Simulation stop time      

%Target location
targetX = 5;
targetY = 8;

start = [x0, y0, 6];
goal = [targetX, targetY, 6];

% Waypoints
[waypoints,timespot,way, T_stop] = ...
    pathplanning(scenario,number_waypoints,start,goal);

%% package ground contact properties
pkgGrndStiff = 10000;
pkgGrndDamp = 30;
pkgGrndTransW = 1e-6;

%% package size and density
pkgSize = [1 1 1]*0.15; % m
pkgDensity = 5; % kg/m^3

%% Motor Parameters
p    = 3;        % Number of pole pairs
Rs   = 0.001;   % Stator resistance per phase           [Ohm]
Ls   = 2e-5;     % Stator self-inductance per phase, Ls  [H]
Ms   = 1e-5;     % Stator mutual inductance, Ms          [H]
psim = 0.0023;%0.0175/4; % Maximum permanent magnet flux linkage [Wb]
Jm   = 9.866e-5;%0.0005;   % Rotor inertia                         [Kg*m^2]
Vdc  = 12.6;     % DC link voltage                       [V]

Imax = 8;
Tmax = 2*p*psim*Imax;
motorDamping = 0; %N*m/(rad/s)

%% Motor speed control parameters
% kp_attitude = 13.1;
% ki_attitude = 2.0;
% kd_attitude = 41;
kp_attitude = 8.567;
ki_attitude = 1.8501;
kd_attitude = 39.1;

% kp_altitude = 0.27;
% ki_altitude = 0.07;
% kd_altitude = 0.35;
kp_altitude = 0.27;
ki_altitude = 0.07;
kd_altitude = 0.35;
Ts = 0.0001;